<BG>:
  size: self.size
  pos: self.pos
  canvas:
    Color:
      rgba: 1,1,1,1
    RoundedRectangle:
      pos: self.pos
      size: self.size
      radius: [self.r,self.r,self.r,self.r]

<Grid>:
  size: self.size
  pos: self.pos
  canvas:
    Color:
      rgba: 1,1,1,1
    Rectangle:
      pos: self.pos
      size: self.size
      source: self.src

<Game>:
  bg: bg
  BG:
    id: bg
    size: self.parent.proper_w,self.parent.proper_h
    center: self.parent.center
